name: pack
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # State management packages
  bloc: ^9.0.0           # Bloc pattern implementation
  flutter_bloc: ^9.1.0                   # Core library for Bloc pattern

  # Image and Media Related Packages
  cached_network_image: ^3.3.0    # For caching and loading network images
  flutter_svg: ^2.0.17            # For rendering SVG images (using latest version, removed duplicate)
  image_picker: ^1.1.2            # For picking images from gallery/camera (using latest version, removed duplicate)

  # State Management and Utilities
  dartz: ^0.10.1                 # Functional programming utilities
  formz: ^0.6.1                  # Form validation helper
  get_it: ^8.0.3                 # Service locator for dependency injection
  equatable: ^2.0.7              # Simplify equality comparisons

  # UI Components and Animations
  google_fonts: ^6.2.1           # Google Fonts integration (using latest version, removed duplicate)
  pinput: ^3.0.1                 # PIN input field widget
  font_awesome_flutter: ^10.8.0  # Font Awesome icons
  lottie: ^3.3.1                 # Lottie animation support

  # Networking and API
  http: ^1.1.2                   # Basic HTTP client
  dio: ^5.8.0+1                  # Powerful HTTP client with additional features
  web_socket_channel: ^3.0.2     # WebSocket communication

  # Localization and Formatting
  intl: ^0.20.2                  # Internationalization and localization
  intl_phone_field: ^3.2.0       # International phone number input field

  # Device and Platform Features
  url_launcher: ^6.3.1           # Launch URLs in browser/apps
  shared_preferences: ^2.5.2     # Persistent key-value storage
  geolocator: ^13.0.2            # Location services
  connectivity_plus: ^6.1.3      # Network connectivity monitoring
  permission_handler: ^11.4.0    # Manage runtime permissions
  flutter_secure_storage: ^9.2.4 # Secure storage for sensitive data
  package_info_plus: ^8.3.0      # Get package information


  # Navigation and Routing
#  go_router: ^14.8.1             # Modern routing solution

  # Debugging and Logging
  logger: ^2.5.0                 # Pretty logging utility

  # Testing and Code Quality
  mockito: ^5.4.5

  # Loading Indicator
  flutter_spinkit: ^5.2.0        # Loading indicators collection
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  device_info_plus: ^11.3.3
  flutter_localization: ^0.3.2
  image_cropper: ^9.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0          # Recommended lints for Flutter

flutter:
  # Assets configuration (uncomment to use)
  assets:
    - assets/images/
    - assets/svg/
    - assets/Illustration/
    - assets/svg/server/
    - assets/translations/

  # Fonts configuration (uncomment to use)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
